### ISSUE TITLE
Можно ли работать в этой компании?

### ISSUE THREAD

**Issue by NightFlexer** [viktor-zharikov/medods#1]
Стоит ли работать в этой компании?

**Comment by NightFlexer** [comment]
Ладно, вопрос больше не актуален)

**Comment by NightFlexer** [comment]
Закрывю

**Comment by viktor-zharikov** [comment]
смотря кем, смотря амбиции...
но не обманывают, начальник адекватный, коллеги у меня тоже вроде были норм
